## Filtering and Merging 2021VAERS Datasets & Filtering Global Vaccination Dataset

In [1]:
# Import dependencies
import pandas as pd

from sqlalchemy import create_engine

### 2021 VAERS Datasets-Data Filtering and Cleaning

#### 2021VAERSVAX.csv: Filter the data based on vaccination type = COVID19,  and remove unneeded columns

In [2]:
# Import data file
VAERSvax = "dataUsed/2021VAERSVAX.csv"

# Read data file, need the encoding to read properly
VAERSvax_raw = pd.read_csv(VAERSvax, encoding="ISO-8859-1")
display(VAERSvax_raw.head(5))
display(VAERSvax_raw.tail(5))

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,916710,COVID19,MODERNA,NaN,1,IM,LA,COVID19 (COVID19 (MODERNA))
1,916741,COVID19,PFIZER\BIONTECH,EH9899,1,SYR,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
2,916742,COVID19,PFIZER\BIONTECH,NaN,1,IM,NaN,COVID19 (COVID19 (PFIZER-BIONTECH))
3,916746,COVID19,MODERNA,037K20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
4,916772,COVID19,PFIZER\BIONTECH,EJ1685,UNK,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
3009,983720,COVID19,MODERNA,039K20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
3010,983721,COVID19,MODERNA,039K20A,1,IM,RA,COVID19 (COVID19 (MODERNA))
3011,983766,COVID19,MODERNA,013L20A,1,IM,RA,COVID19 (COVID19 (MODERNA))
3012,983919,COVID19,MODERNA,030L20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
3013,985205,COVID19,MODERNA,029L20A,1,IM,UN,COVID19 (COVID19 (MODERNA))

In [3]:
# Extract the columns names
columns = list(VAERSvax_raw.columns)
columns

['VAERS_ID',
 'VAX_TYPE',
 'VAX_MANU',
 'VAX_LOT',
 'VAX_DOSE_SERIES',
 'VAX_ROUTE',
 'VAX_SITE',
 'VAX_NAME']

In [4]:
# Create a dataframe with the wanted columns only
wanted_columns = VAERSvax_raw[['VAERS_ID',
 'VAX_TYPE',
 'VAX_MANU',
 'VAX_DOSE_SERIES',
 'VAX_SITE'
]]
display(wanted_columns.head(5))
display(wanted_columns.tail(5))

   VAERS_ID VAX_TYPE         VAX_MANU VAX_DOSE_SERIES VAX_SITE
0    916710  COVID19          MODERNA               1       LA
1    916741  COVID19  PFIZER\BIONTECH               1       LA
2    916742  COVID19  PFIZER\BIONTECH               1      NaN
3    916746  COVID19          MODERNA               1       LA
4    916772  COVID19  PFIZER\BIONTECH             UNK       LA

      VAERS_ID VAX_TYPE VAX_MANU VAX_DOSE_SERIES VAX_SITE
3009    983720  COVID19  MODERNA               1       LA
3010    983721  COVID19  MODERNA               1       RA
3011    983766  COVID19  MODERNA               1       RA
3012    983919  COVID19  MODERNA               1       LA
3013    985205  COVID19  MODERNA               1       UN

In [5]:
# Filter the data by vax_type = COVID19
# Reset index
filtered_data = wanted_columns[wanted_columns["VAX_TYPE"]=="COVID19"]
filtered_data.reset_index(drop=True, inplace=True)
display(filtered_data.head(5))
display(filtered_data.tail(5))

   VAERS_ID VAX_TYPE         VAX_MANU VAX_DOSE_SERIES VAX_SITE
0    916710  COVID19          MODERNA               1       LA
1    916741  COVID19  PFIZER\BIONTECH               1       LA
2    916742  COVID19  PFIZER\BIONTECH               1      NaN
3    916746  COVID19          MODERNA               1       LA
4    916772  COVID19  PFIZER\BIONTECH             UNK       LA

      VAERS_ID VAX_TYPE VAX_MANU VAX_DOSE_SERIES VAX_SITE
2839    983720  COVID19  MODERNA               1       LA
2840    983721  COVID19  MODERNA               1       RA
2841    983766  COVID19  MODERNA               1       RA
2842    983919  COVID19  MODERNA               1       LA
2843    985205  COVID19  MODERNA               1       UN

#### 2021VAERSData.csv

In [6]:
# Import data file
VAERSData = "dataUsed/2021VAERSData.csv"

# Read data file, need the encoding to read properly
vaer_data_raw = pd.read_csv(VAERSData, encoding="ISO-8859-1")
display(vaer_data_raw.head(2))
display(vaer_data_raw.tail(2))

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,916710,01/01/2021,MO,23.0,23.0,NaN,F,NaN,"Acute appendicitis, onset morning of 1/1/2021 ...",NaN,...,NaN,Hypothyroidism,NaN,NaN,2,01/01/2021,NaN,NaN,Y,NKDA
1,916741,01/01/2021,AR,68.0,68.0,NaN,F,NaN,"on dec 22 I felt some myalgias, chills, fatigu...",NaN,...,had surgery R hand for advanced arthritis 11/1...,Rheumatoid arthritis - mostly affecting R wris...,NaN,NaN,2,01/01/2021,NaN,NaN,NaN,bee stings

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
2944,983919,01/28/2021,FL,69.0,69.0,NaN,M,NaN,death,Y,...,NaN,NaN,NaN,NaN,2,01/28/2021,NaN,NaN,NaN,NaN
2945,985205,01/29/2021,OH,75.0,75.0,NaN,M,NaN,Patient was feeling dizzy and under the weathe...,Y,...,No,None,NaN,NaN,2,01/29/2021,NaN,NaN,NaN,No

In [7]:
# Extract the columns names
columns2 = list(vaer_data_raw.columns)
columns2

['VAERS_ID',
 'RECVDATE',
 'STATE',
 'AGE_YRS',
 'CAGE_YR',
 'CAGE_MO',
 'SEX',
 'RPT_DATE',
 'SYMPTOM_TEXT',
 'DIED',
 'DATEDIED',
 'L_THREAT',
 'ER_VISIT',
 'HOSPITAL',
 'HOSPDAYS',
 'X_STAY',
 'DISABLE',
 'RECOVD',
 'VAX_DATE',
 'ONSET_DATE',
 'NUMDAYS',
 'LAB_DATA',
 'V_ADMINBY',
 'V_FUNDBY',
 'OTHER_MEDS',
 'CUR_ILL',
 'HISTORY',
 'PRIOR_VAX',
 'SPLTTYPE',
 'FORM_VERS',
 'TODAYS_DATE',
 'BIRTH_DEFECT',
 'OFC_VISIT',
 'ER_ED_VISIT',
 'ALLERGIES']

In [8]:
# Create a dataframe with the wanted columns only
wanted_columns2 = vaer_data_raw[['VAERS_ID',
 'STATE',
 'AGE_YRS',
 'SEX',
 'DIED',
 'DATEDIED',
 'L_THREAT',
 'ER_VISIT',
 'HOSPITAL',
 'HOSPDAYS',
 'X_STAY',
 'DISABLE',
 'RECOVD',
 'VAX_DATE',
 'ONSET_DATE',
 'NUMDAYS'
]]
wanted_columns2.head(5)

,VAERS_ID,STATE,AGE_YRS,SEX,DIED,DATEDIED,L_THREAT,ER_VISIT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS
0,916710,MO,23.0,F,NaN,NaN,Y,NaN,Y,NaN,NaN,NaN,U,12/29/2020,01/01/2021,3.0
1,916741,AR,68.0,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,N,12/21/2020,12/22/2020,1.0
2,916742,MN,29.0,F,NaN,NaN,Y,NaN,Y,4.0,NaN,NaN,U,12/29/2020,12/29/2020,0.0
3,916746,TX,49.0,F,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,12/28/2020,12/28/2020,0.0
4,916772,GA,55.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,12/22/2020,12/26/2020,4.0

#### 2021VAERSSymptoms.csv

In [9]:
# Import data file
VAERSsymptoms = "dataUsed/2021VAERSSYMPTOMS.csv"

# Read data file, need the encoding to read properly
vaer_symptoms_raw = pd.read_csv(VAERSsymptoms, encoding="ISO-8859-1")
display(vaer_symptoms_raw.head(2))
display(vaer_symptoms_raw.tail(2))

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,916710,Appendicitis,23.1,Band neutrophil percentage increased,23.1,Surgery,23.1,White blood cell count increased,23.1,NaN,NaN
1,916741,Chills,23.1,Complex regional pain syndrome,23.1,Fatigue,23.1,Headache,23.1,Joint range of motion decreased,23.1

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
4710,983919,Death,23.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4711,985205,Death,23.1,Dizziness,23.1,Malaise,23.1,NaN,NaN,NaN,NaN

In [10]:
# Extract the columns names
columns3 = list(vaer_symptoms_raw.columns)
columns3

['VAERS_ID',
 'SYMPTOM1',
 'SYMPTOMVERSION1',
 'SYMPTOM2',
 'SYMPTOMVERSION2',
 'SYMPTOM3',
 'SYMPTOMVERSION3',
 'SYMPTOM4',
 'SYMPTOMVERSION4',
 'SYMPTOM5',
 'SYMPTOMVERSION5']

In [11]:
# Create a dataframe with the wanted columns only
wanted_columns3 = vaer_symptoms_raw[['VAERS_ID',
 'SYMPTOM1',
 'SYMPTOM2',
 'SYMPTOM3',
 'SYMPTOM4',
 'SYMPTOM5'
]]
wanted_columns3.tail(5)

,VAERS_ID,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
4707,983721,Death,NaN,NaN,NaN,NaN
4708,983766,Blood pH decreased,Cardiac failure acute,Chest discomfort,Death,Dyspnoea
4709,983766,International normalised ratio increased,N-terminal prohormone brain natriuretic peptid...,SARS-CoV-2 test negative,NaN,NaN
4710,983919,Death,NaN,NaN,NaN,NaN
4711,985205,Death,Dizziness,Malaise,NaN,NaN

### 2021 VAERS Datasets-Merging

In [12]:
# Merge the two organized dataframes
merge_2data = pd.merge(filtered_data,wanted_columns2, on="VAERS_ID", how="left")
display(merge_2data.head(2))
display(merge_2data.tail(2))

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,L_THREAT,ER_VISIT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS
0,916710,COVID19,MODERNA,1,LA,MO,23.0,F,NaN,NaN,Y,NaN,Y,NaN,NaN,NaN,U,12/29/2020,01/01/2021,3.0
1,916741,COVID19,PFIZER\BIONTECH,1,LA,AR,68.0,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,N,12/21/2020,12/22/2020,1.0

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,L_THREAT,ER_VISIT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS
2842,983919,COVID19,MODERNA,1,LA,FL,69.0,M,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/21/2021,01/01/2021,NaN
2843,985205,COVID19,MODERNA,1,UN,OH,75.0,M,Y,01/26/2021,NaN,NaN,NaN,NaN,NaN,NaN,N,01/25/2021,01/26/2021,1.0

In [13]:
# Merge all three organized dataframes
merge_all = pd.merge(merge_2data,wanted_columns3,on="VAERS_ID", how="left")
display(merge_all.head(4))
display(merge_all.tail(4))

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916710,COVID19,MODERNA,1,LA,MO,23.0,F,NaN,NaN,...,NaN,U,12/29/2020,01/01/2021,3.0,Appendicitis,Band neutrophil percentage increased,Surgery,White blood cell count increased,NaN
1,916741,COVID19,PFIZER\BIONTECH,1,LA,AR,68.0,F,NaN,NaN,...,Y,N,12/21/2020,12/22/2020,1.0,Chills,Complex regional pain syndrome,Fatigue,Headache,Joint range of motion decreased
2,916741,COVID19,PFIZER\BIONTECH,1,LA,AR,68.0,F,NaN,NaN,...,Y,N,12/21/2020,12/22/2020,1.0,Myalgia,Pain in extremity,Peripheral swelling,X-ray abnormal,NaN
3,916742,COVID19,PFIZER\BIONTECH,1,NaN,MN,29.0,F,NaN,NaN,...,NaN,U,12/29/2020,12/29/2020,0.0,Anaphylactic reaction,Blood test,Burning sensation,Central venous catheterisation,Dysphonia

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
4563,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,NaN,N,01/16/2021,01/21/2021,5.0,Blood pH decreased,Cardiac failure acute,Chest discomfort,Death,Dyspnoea
4564,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,NaN,N,01/16/2021,01/21/2021,5.0,International normalised ratio increased,N-terminal prohormone brain natriuretic peptid...,SARS-CoV-2 test negative,NaN,NaN
4565,983919,COVID19,MODERNA,1,LA,FL,69.0,M,Y,NaN,...,NaN,NaN,01/21/2021,01/01/2021,NaN,Death,NaN,NaN,NaN,NaN
4566,985205,COVID19,MODERNA,1,UN,OH,75.0,M,Y,01/26/2021,...,NaN,N,01/25/2021,01/26/2021,1.0,Death,Dizziness,Malaise,NaN,NaN

# Data Checking

### All Symtoms

In [14]:
# Pull out symptom 1
sym_one = merge_all[["SYMPTOM1"]]
sym_one

                                      SYMPTOM1
0                                 Appendicitis
1                                       Chills
2                                      Myalgia
3                        Anaphylactic reaction
4                               Intensive care
...                                        ...
4562                                     Death
4563                        Blood pH decreased
4564  International normalised ratio increased
4565                                     Death
4566                                     Death

[4567 rows x 1 columns]

In [15]:
# Check the symptom 2
sym_two = merge_all[["SYMPTOM2"]]
sym_two

                                               SYMPTOM2
0                  Band neutrophil percentage increased
1                        Complex regional pain syndrome
2                                     Pain in extremity
3                                            Blood test
4                                              Pruritus
...                                                 ...
4562                                                NaN
4563                              Cardiac failure acute
4564  N-terminal prohormone brain natriuretic peptid...
4565                                                NaN
4566                                          Dizziness

[4567 rows x 1 columns]

In [16]:
# Check the symptom 3
sym_three = merge_all[["SYMPTOM3"]]
sym_three

                      SYMPTOM3
0                      Surgery
1                      Fatigue
2          Peripheral swelling
3            Burning sensation
4                         Rash
...                        ...
4562                       NaN
4563          Chest discomfort
4564  SARS-CoV-2 test negative
4565                       NaN
4566                   Malaise

[4567 rows x 1 columns]

In [17]:
# Check the symptom 4
sym_four = merge_all[["SYMPTOM4"]]
sym_four

                              SYMPTOM4
0     White blood cell count increased
1                             Headache
2                       X-ray abnormal
3       Central venous catheterisation
4                         Rash macular
...                                ...
4562                               NaN
4563                             Death
4564                               NaN
4565                               NaN
4566                               NaN

[4567 rows x 1 columns]

In [18]:
# Check the symptom 5
sym_five = merge_all[["SYMPTOM5"]]
sym_five

                             SYMPTOM5
0                                 NaN
1     Joint range of motion decreased
2                                 NaN
3                           Dysphonia
4                    Throat tightness
...                               ...
4562                              NaN
4563                         Dyspnoea
4564                              NaN
4565                              NaN
4566                              NaN

[4567 rows x 1 columns]

In [19]:
# Combine all columns into one
sym_combine = pd.concat(map(merge_all.get, ["SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5"])).reset_index(drop=True)
sym_combine

0                 Appendicitis
1                       Chills
2                      Myalgia
3        Anaphylactic reaction
4               Intensive care
                 ...
22830                      NaN
22831                 Dyspnoea
22832                      NaN
22833                      NaN
22834                      NaN
Length: 22835, dtype: object

In [20]:
# Turn it into a dataframe
sym_combine_df = pd.DataFrame(sym_combine)
sym_combine_df

                           0
0               Appendicitis
1                     Chills
2                    Myalgia
3      Anaphylactic reaction
4             Intensive care
...                      ...
22830                    NaN
22831               Dyspnoea
22832                    NaN
22833                    NaN
22834                    NaN

[22835 rows x 1 columns]

In [21]:
# Get the count for each symptom
testing = pd.DataFrame(sym_combine_df.value_counts())
testing_count = testing.rename(columns={0:"count"})
testing_count.head(20)

                          count
0
SARS-CoV-2 test positive    575
Headache                    362
Death                       359
Pyrexia                     358
Dyspnoea                    310
Fatigue                     269
Dizziness                   257
Nausea                      246
Chills                      246
Pain                        246
Pain in extremity           198
SARS-CoV-2 test negative    161
Malaise                     155
Cough                       153
Asthenia                    152
Vomiting                    143
Hypoaesthesia               130
Paraesthesia                125
Myalgia                     120
COVID-19                    117

### Dose 1 All Symptoms

In [22]:
# Groupby dose
all_dose = merge_all.groupby("VAX_DOSE_SERIES")
all_dose.tail(10)

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
273,918552,COVID19,MODERNA,5,LA,IL,39.0,F,NaN,NaN,...,NaN,Y,12/30/2020,01/01/2021,2.0,Chills,Diarrhoea,Influenza virus test negative,Nausea,Pyrexia
274,918552,COVID19,MODERNA,5,LA,IL,39.0,F,NaN,NaN,...,NaN,Y,12/30/2020,01/01/2021,2.0,SARS-CoV-2 test negative,NaN,NaN,NaN,NaN
1947,940602,COVID19,MODERNA,5,LA,TX,83.0,M,Y,NaN,...,NaN,NaN,01/08/2021,01/10/2021,2.0,Death,Injection site pain,Myocardial infarction,Pain,Syncope
2348,946780,COVID19,MODERNA,NaN,NaN,FL,33.0,F,NaN,NaN,...,NaN,N,12/04/2020,01/12/2021,39.0,Angiogram cerebral abnormal,Cerebral haemorrhage,Cerebral venous sinus thrombosis,Computerised tomogram head abnormal,Decompressive craniectomy
2349,946780,COVID19,MODERNA,NaN,NaN,FL,33.0,F,NaN,NaN,...,NaN,N,12/04/2020,01/12/2021,39.0,Hemiparesis,Subarachnoid haemorrhage,NaN,NaN,NaN
3495,963904,COVID19,PFIZER\BIONTECH,4,LA,NaN,27.0,F,NaN,NaN,...,NaN,N,01/11/2021,01/11/2021,0.0,Asthenia,Capillary nail refill test,Grip strength decreased,Hypoaesthesia,Impaired work ability
3496,963904,COVID19,PFIZER\BIONTECH,4,LA,NaN,27.0,F,NaN,NaN,...,NaN,N,01/11/2021,01/11/2021,0.0,Injected limb mobility decreased,Nerve injury,Paraesthesia,NaN,NaN
3797,969219,COVID19,MODERNA,7+,LA,SC,61.0,M,Y,01/24/2021,...,NaN,N,01/23/2021,01/24/2021,1.0,Death,Syncope,NaN,NaN,NaN
3910,971271,COVID19,PFIZER\BIONTECH,3,NaN,NY,74.0,F,NaN,NaN,...,NaN,U,01/12/2021,01/12/2021,0.0,Extra dose administered,Immediate post-injection reaction,SARS-CoV-2 test,Somnolence,NaN
4445,976939,COVID19,PFIZER\BIONTECH,2,LA,NJ,50.0,F,NaN,NaN,...,Y,N,01/12/2021,01/12/2021,0.0,Muscle contractions involuntary,Muscle spasms,Myalgia,Nausea,Pain
4446,976939,COVID19,PFIZER\BIONTECH,2,LA,NJ,50.0,F,NaN,NaN,...,Y,N,01/12/2021,01/12/2021,0.0,Pallor,Paraesthesia oral,SARS-CoV-2 test negative,Sensitive skin,Tachypnoea
4447,976939,COVID19,PFIZER\BIONTECH,2,LA,NJ,50.0,F,NaN,NaN,...,Y,N,01/12/2021,01/12/2021,0.0,Tremor,NaN,NaN,NaN,NaN
4449,976965,COVID19,PFIZER\BIONTECH,2,LA,AZ,45.0,M,NaN,NaN,...,NaN,N,01/13/2021,01/14/2021,1.0,Acute myocardial infarction,Arteriospasm coronary,Arthralgia,Burning sensation,Catheterisation cardiac normal
4450,976965,COVID19,PFIZER\BIONTECH,2,LA,AZ,45.0,M,NaN,NaN,...,NaN,N,01/13/2021,01/14/2021,1.0,Chest pain,Echocardiogram normal,Ejection fraction normal,Electrocardiogram ST segment elevation,Lymphadenopathy
4451,976965,COVID19,PFIZER\BIONTECH,2,LA,AZ,45.0,M,NaN,NaN,...,NaN,N,01/13/2021,01/14/2021,1.0,Myalgia,Pyrexia,SARS-CoV-2 test negative,Tachycardia,Troponin increased
4482,978876,COVID19,PFIZER\BIONTECH,UNK,NaN,NaN,NaN,M,Y,NaN,...,NaN,N,NaN,NaN,NaN,Autoimmune disorder,Death,NaN,NaN,NaN
4487,979155,COVID19,PFIZER\BIONTECH,UNK,RA,AZ,65.0,M,Y,01/23/2021,...,NaN,N,01/03/2021,01/04/2021,1.0,Aphasia,Chills,Headache,Influenza A virus test positive,Neck pain
4488,979155,COVID19,PFIZER\BIONTECH,UNK,RA,AZ,65.0,M,Y,01/23/2021,...,NaN,N,01/03/2021,01/04/2021,1.0,Vomiting,NaN,NaN,NaN,NaN
4505,979837,COVID19,PFIZER\BIONTECH,UNK,NaN,NV,76.0,M,Y,01/27/2021,...,NaN,N,01/25/2021,01/27/2021,2.0,Cardiac arrest,Cardioversion,Death,Hypotension,Presyncope
4506,979837,COVID19,PFIZER\BIONTECH,UNK,NaN,NV,76.0,M,Y,01/27/2021,...,NaN,N,01/25/2021,01/27/2021,2.0,Pulseless electrical activity,Resuscitation,Ventricular fibrillation,NaN,NaN
4509,979990,COVID19,MODERNA,UNK,NaN,OH,63.0,M,Y,01/09/2021,...,NaN,N,01/07/2021,01/09/2021,2.0,Cardiac arrest,NaN,NaN,NaN,NaN
4513,981141,COVID19,PFIZER\BIONTECH,2,LA,GA,34.0,F,NaN,NaN,...,NaN,U,01/22/2021,01/23/2021,1.0,Chills,Dyspnoea,Pain,Pyrexia,NaN
4514,981225,COVID19,PFIZER\BIONTECH,2,UN,MD,59.0,F,Y,01/27/2021,...,NaN,N,01/27/2021,01/27/2021,0.0,Abdominal pain,Death,Pulse absent,Unresponsive to stimuli,Vomiting
4518,981849,COVID19,MODERNA,UNK,LA,IN,92.0,M,Y,01/16/2021,...,NaN,N,01/13/2021,01/16/2021,3.0,Death,NaN,NaN,NaN,NaN
4519,981912,COVID19,MODERNA,2,UN,CA,67.0,F,Y,01/27/2021,...,NaN,N,01/23/2021,01/23/2021,0.0,Angiogram pulmonary abnormal,Cardiac arrest,Chest pain,Cold sweat,Death
4520,981912,COVID19,MODERNA,2,UN,CA,67.0,F,Y,01/27/2021,...,NaN,N,01/23/2021,01/23/2021,0.0,Endotracheal intubation,Hypotension,Laboratory test,Pallor,Pulmonary embolism
4525,982354,COVID19,MODERNA,UNK,NaN,NaN,91.0,M,Y,01/23/2021,...,NaN,NaN,12/29/2020,01/23/2021,25.0,Death,NaN,NaN,NaN,NaN
4526,982370,COVID19,MODERNA,UNK,LA,KY,93.0,M,Y,01/16/2021,...,NaN,N,01/14/2021,01/16/2021,2.0,Death,NaN,NaN,NaN,NaN
4530,982517,COVID19,MODERNA,UNK,NaN,NaN,66.0,M,Y,01/25/2021,...,NaN,NaN,01/11/2021,01/25/2021,14.0,Death,NaN,NaN,NaN,NaN
4557,983428,COVID19,MODERNA,1,NaN,NE,68.0,F,Y,01/18/2021,...,NaN,N,12/24/2020,01/06/2021,13.0,Death,Dehydration,Fatigue,Haemoglobin decreased,Hypertension
4558,983428,COVID19,MODERNA,1,NaN,NE,68.0,F,Y,01/18/2021,...,NaN,N,12/24/2020,01/06/2021,13.0,Lung infiltration,Procalcitonin increased,Sepsis,Staphylococcal bacteraemia,Vomiting
4559,983428,COVID19,MODERNA,1,NaN,NE,68.0,F,Y,01/18/2021,...,NaN,N,12/24/2020,01/06/2021,13.0,White blood cell count increased,NaN,NaN,NaN,NaN
4560,983482,COVID19,PFIZER\BIONTECH,1,RA,CA,90.0,M,Y,01/24/2021,...,NaN,N,01/20/2021,01/20/2021,0.0,Cerebrovascular accident,Death,NaN,NaN,NaN
4561,983720,COVID19,MODERNA,1,LA,NaN,76.0,M,Y,01/20/2021,...,NaN,U,12/30/2020,01/20/2021,21.0,Death,NaN,NaN,NaN,NaN
4562,983721,COVID19,MODERNA,1,RA,NaN,72.0,M,Y,01/23/2021,...,NaN,U,01/13/2021,01/23/2021,10.0,Death,NaN,NaN,NaN,NaN
4563,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,NaN,N,01/16/2021,01/21/2021,5.0,Blood pH decreased,Cardiac failure acute,Chest discomfort,Death,Dyspnoea
4564,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,NaN,N,01/16/2021,01/21/2021,5.0,International normalised ratio increased,N-terminal prohormone brain natriuretic peptid...,SARS-CoV-2 test negative,NaN,NaN
4565,983919,COVID19,MODERNA,1,LA,FL,69.0,M,Y,NaN,...,NaN,NaN,01/21/2021,01/01/2021,NaN,Death,NaN,NaN,NaN,NaN
4566,985205,COVID19,MODERNA,1,UN,OH,75.0,M,Y,01/26/2021,...,NaN,N,01/25/2021,01/26/2021,1.0,Death,Dizziness,Malaise,NaN,NaN

In [23]:
# Extracting dose 1 from dose series
dose_one = merge_all.loc[merge_all["VAX_DOSE_SERIES"]=="1"]
dose_one

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916710,COVID19,MODERNA,1,LA,MO,23.0,F,NaN,NaN,...,NaN,U,12/29/2020,01/01/2021,3.0,Appendicitis,Band neutrophil percentage increased,Surgery,White blood cell count increased,NaN
1,916741,COVID19,PFIZER\BIONTECH,1,LA,AR,68.0,F,NaN,NaN,...,Y,N,12/21/2020,12/22/2020,1.0,Chills,Complex regional pain syndrome,Fatigue,Headache,Joint range of motion decreased
2,916741,COVID19,PFIZER\BIONTECH,1,LA,AR,68.0,F,NaN,NaN,...,Y,N,12/21/2020,12/22/2020,1.0,Myalgia,Pain in extremity,Peripheral swelling,X-ray abnormal,NaN
3,916742,COVID19,PFIZER\BIONTECH,1,NaN,MN,29.0,F,NaN,NaN,...,NaN,U,12/29/2020,12/29/2020,0.0,Anaphylactic reaction,Blood test,Burning sensation,Central venous catheterisation,Dysphonia
4,916742,COVID19,PFIZER\BIONTECH,1,NaN,MN,29.0,F,NaN,NaN,...,NaN,U,12/29/2020,12/29/2020,0.0,Intensive care,Pruritus,Rash,Rash macular,Throat tightness
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4562,983721,COVID19,MODERNA,1,RA,NaN,72.0,M,Y,01/23/2021,...,NaN,U,01/13/2021,01/23/2021,10.0,Death,NaN,NaN,NaN,NaN
4563,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,NaN,N,01/16/2021,01/21/2021,5.0,Blood pH decreased,Cardiac failure acute,Chest discomfort,Death,Dyspnoea
4564,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,NaN,N,01/16/2021,01/21/2021,5.0,International normalised ratio increased,N-terminal prohormone brain natriuretic peptid...,SARS-CoV-2 test negative,NaN,NaN
4565,983919,COVID19,MODERNA,1,LA,FL,69.0,M,Y,NaN,...,NaN,NaN,01/21/2021,01/01/2021,NaN,Death,NaN,NaN,NaN,NaN
4566,985205,COVID19,MODERNA,1,UN,OH,75.0,M,Y,01/26/2021,...,NaN,N,01/25/2021,01/26/2021,1.0,Death,Dizziness,Malaise,NaN,NaN

#### Filter by Dates

In [24]:
# Identify dates
doseOneDates = dose_one["VAX_DATE"]
doseOneDatesList = list(doseOneDates.unique())
doseOneDatesList

['12/29/2020',
 '12/21/2020',
 '12/28/2020',
 '12/26/2020',
 '12/23/2020',
 '12/24/2020',
 '12/31/2020',
 '12/01/2020',
 '12/27/2020',
 '12/22/2020',
 '12/30/2020',
 '01/03/2021',
 '12/20/2020',
 '01/02/2021',
 '12/17/2020',
 '12/14/2020',
 '01/04/2021',
 '12/18/2020',
 nan,
 '12/19/2020',
 '01/02/2020',
 '12/16/2020',
 '12/25/2020',
 '01/04/2020',
 '12/15/2020',
 '01/05/2021',
 '01/06/2021',
 '01/07/2021',
 '01/01/2021',
 '01/08/2021',
 '01/09/2021',
 '01/11/2021',
 '01/12/2021',
 '01/10/2021',
 '01/13/2021',
 '01/14/2021',
 '01/15/2021',
 '01/16/2021',
 '01/17/2021',
 '01/18/2021',
 '10/02/1982',
 '01/19/2021',
 '01/20/2021',
 '01/21/2021',
 '01/22/2021',
 '11/30/1983',
 '01/23/2021',
 '01/24/2021',
 '12/10/2020',
 '01/25/2021',
 '01/18/1920',
 '01/22/2020',
 '11/17/2020',
 '01/26/2021']

In [27]:
# Turn into a dataframe for organization
doseOneDatesDf = pd.DataFrame(doseOneDatesList)
doseOneDatesDf

             0
0   12/29/2020
1   12/21/2020
2   12/28/2020
3   12/26/2020
4   12/23/2020
5   12/24/2020
6   12/31/2020
7   12/01/2020
8   12/27/2020
9   12/22/2020
10  12/30/2020
11  01/03/2021
12  12/20/2020
13  01/02/2021
14  12/17/2020
15  12/14/2020
16  01/04/2021
17  12/18/2020
18         NaN
19  12/19/2020
20  01/02/2020
21  12/16/2020
22  12/25/2020
23  01/04/2020
24  12/15/2020
25  01/05/2021
26  01/06/2021
27  01/07/2021
28  01/01/2021
29  01/08/2021
30  01/09/2021
31  01/11/2021
32  01/12/2021
33  01/10/2021
34  01/13/2021
35  01/14/2021
36  01/15/2021
37  01/16/2021
38  01/17/2021
39  01/18/2021
40  10/02/1982
41  01/19/2021
42  01/20/2021
43  01/21/2021
44  01/22/2021
45  11/30/1983
46  01/23/2021
47  01/24/2021
48  12/10/2020
49  01/25/2021
50  01/18/1920
51  01/22/2020
52  11/17/2020
53  01/26/2021

In [28]:
# Check type
doseOneDatesDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       53 non-null     object
dtypes: object(1)
memory usage: 560.0+ bytes

In [29]:
# Convert to datetime type
doseOneDatesDf[0]=doseOneDatesDf[0].astype('datetime64[ns]')
doseOneDatesDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       53 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 560.0 bytes

In [30]:
# Organize
doseOneDatesDf = doseOneDatesDf.sort_values(by=0)
doseOneDatesDf.reset_index(drop=True, inplace=True)
doseOneDatesDf

            0
0  1920-01-18
1  1982-10-02
2  1983-11-30
3  2020-01-02
4  2020-01-04
5  2020-01-22
6  2020-11-17
7  2020-12-01
8  2020-12-10
9  2020-12-14
10 2020-12-15
11 2020-12-16
12 2020-12-17
13 2020-12-18
14 2020-12-19
15 2020-12-20
16 2020-12-21
17 2020-12-22
18 2020-12-23
19 2020-12-24
20 2020-12-25
21 2020-12-26
22 2020-12-27
23 2020-12-28
24 2020-12-29
25 2020-12-30
26 2020-12-31
27 2021-01-01
28 2021-01-02
29 2021-01-03
30 2021-01-04
31 2021-01-05
32 2021-01-06
33 2021-01-07
34 2021-01-08
35 2021-01-09
36 2021-01-10
37 2021-01-11
38 2021-01-12
39 2021-01-13
40 2021-01-14
41 2021-01-15
42 2021-01-16
43 2021-01-17
44 2021-01-18
45 2021-01-19
46 2021-01-20
47 2021-01-21
48 2021-01-22
49 2021-01-23
50 2021-01-24
51 2021-01-25
52 2021-01-26
53        NaT

In [34]:
# Drop weird dates
doseOneDatesDf_cleaned = doseOneDatesDf.drop(doseOneDatesDf.index[0:30])
doseOneDatesDf_cleaned = doseOneDatesDf_cleaned.drop([53])
doseOneDatesDf_cleaned.reset_index(drop=True, inplace=True)
doseOneDatesDf_cleaned

            0
0  2021-01-04
1  2021-01-05
2  2021-01-06
3  2021-01-07
4  2021-01-08
5  2021-01-09
6  2021-01-10
7  2021-01-11
8  2021-01-12
9  2021-01-13
10 2021-01-14
11 2021-01-15
12 2021-01-16
13 2021-01-17
14 2021-01-18
15 2021-01-19
16 2021-01-20
17 2021-01-21
18 2021-01-22
19 2021-01-23
20 2021-01-24
21 2021-01-25
22 2021-01-26

In [43]:
# Create a column of the converted datetime formate
dose_one_covert_copy = dose_one.copy()
dose_one_covert = dose_one["VAX_DATE"].astype('datetime64[ns]')
dose_one_covert_copy["CONVERTED_DATE"] = dose_one_covert

In [50]:
# Create a desired date list
date_list = list(doseOneDatesDf_cleaned[0])
date_list

[Timestamp('2021-01-04 00:00:00'),
 Timestamp('2021-01-05 00:00:00'),
 Timestamp('2021-01-06 00:00:00'),
 Timestamp('2021-01-07 00:00:00'),
 Timestamp('2021-01-08 00:00:00'),
 Timestamp('2021-01-09 00:00:00'),
 Timestamp('2021-01-10 00:00:00'),
 Timestamp('2021-01-11 00:00:00'),
 Timestamp('2021-01-12 00:00:00'),
 Timestamp('2021-01-13 00:00:00'),
 Timestamp('2021-01-14 00:00:00'),
 Timestamp('2021-01-15 00:00:00'),
 Timestamp('2021-01-16 00:00:00'),
 Timestamp('2021-01-17 00:00:00'),
 Timestamp('2021-01-18 00:00:00'),
 Timestamp('2021-01-19 00:00:00'),
 Timestamp('2021-01-20 00:00:00'),
 Timestamp('2021-01-21 00:00:00'),
 Timestamp('2021-01-22 00:00:00'),
 Timestamp('2021-01-23 00:00:00'),
 Timestamp('2021-01-24 00:00:00'),
 Timestamp('2021-01-25 00:00:00'),
 Timestamp('2021-01-26 00:00:00')]

In [55]:
# Filter out the content based on the content of date list
dose_one_filter = dose_one_covert_copy[dose_one_covert_copy.CONVERTED_DATE.isin(date_list)]
dose_one_filter.reset_index(drop=True, inplace=True)
dose_one_filter

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,CONVERTED_DATE
0,918086,COVID19,MODERNA,1,LA,NaN,31.0,M,NaN,NaN,...,N,01/04/2021,01/04/2021,0.0,Electrocardiogram abnormal,Intensive care,Sinus tachycardia,Supraventricular tachycardia,NaN,2021-01-04
1,918208,COVID19,PFIZER\BIONTECH,1,LA,IN,62.0,M,NaN,NaN,...,Y,01/04/2021,01/04/2021,0.0,Nasal congestion,Paraesthesia,Paraesthesia oral,NaN,NaN,2021-01-04
2,919559,COVID19,MODERNA,1,LA,OR,40.0,F,NaN,NaN,...,U,01/04/2021,01/04/2021,0.0,Anxiety,Blood pressure increased,Chest discomfort,Dyspnoea,Heart rate decreased,2021-01-04
3,919559,COVID19,MODERNA,1,LA,OR,40.0,F,NaN,NaN,...,U,01/04/2021,01/04/2021,0.0,Loss of consciousness,Nausea,NaN,NaN,NaN,2021-01-04
4,919629,COVID19,PFIZER\BIONTECH,1,LA,OH,51.0,F,NaN,NaN,...,Y,01/04/2021,01/04/2021,0.0,Erythema,Feeling abnormal,Hyperhidrosis,Malaise,Oxygen saturation decreased,2021-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1353,983721,COVID19,MODERNA,1,RA,NaN,72.0,M,Y,01/23/2021,...,U,01/13/2021,01/23/2021,10.0,Death,NaN,NaN,NaN,NaN,2021-01-13
1354,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,N,01/16/2021,01/21/2021,5.0,Blood pH decreased,Cardiac failure acute,Chest discomfort,Death,Dyspnoea,2021-01-16
1355,983766,COVID19,MODERNA,1,RA,NC,90.0,F,Y,01/24/2021,...,N,01/16/2021,01/21/2021,5.0,International normalised ratio increased,N-terminal prohormone brain natriuretic peptid...,SARS-CoV-2 test negative,NaN,NaN,2021-01-16
1356,983919,COVID19,MODERNA,1,LA,FL,69.0,M,Y,NaN,...,NaN,01/21/2021,01/01/2021,NaN,Death,NaN,NaN,NaN,NaN,2021-01-21
1357,985205,COVID19,MODERNA,1,UN,OH,75.0,M,Y,01/26/2021,...,N,01/25/2021,01/26/2021,1.0,Death,Dizziness,Malaise,NaN,NaN,2021-01-25

In [61]:
# Get count of patients
dose_one_filter["VAX_DOSE_SERIES"].value_counts()

1    1358
Name: VAX_DOSE_SERIES, dtype: int64

In [56]:
# Combine all columns into one
dose_combine = pd.concat(map(dose_one_filter.get, ["SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5"])).reset_index(drop=True)
dose_combine

0       Electrocardiogram abnormal
1                 Nasal congestion
2                          Anxiety
3            Loss of consciousness
4                         Erythema
                   ...
6785                           NaN
6786                      Dyspnoea
6787                           NaN
6788                           NaN
6789                           NaN
Length: 6790, dtype: object

In [57]:
# Turn it into a dataframe
dose_combine_df = pd.DataFrame(dose_combine)
dose_combine_df

                               0
0     Electrocardiogram abnormal
1               Nasal congestion
2                        Anxiety
3          Loss of consciousness
4                       Erythema
...                          ...
6785                         NaN
6786                    Dyspnoea
6787                         NaN
6788                         NaN
6789                         NaN

[6790 rows x 1 columns]

#### Dose 1

In [58]:
# Get the count for each symptom
dose_one_sym = pd.DataFrame(dose_combine_df.value_counts())
dose_one_sym_count = dose_one_sym.rename(columns={0:"count"})
dose_one_sym_count.reset_index(drop=False, inplace=True)
dose_one_sym_count.head(20)

                           0  count
0                      Death    183
1                   Dyspnoea    115
2                    Pyrexia     99
3                   Headache     94
4                  Dizziness     91
5                     Nausea     75
6                    Fatigue     65
7    Unresponsive to stimuli     61
8                   Vomiting     56
9                     Chills     55
10                      Pain     55
11  SARS-CoV-2 test positive     53
12                  Asthenia     52
13             Hypoaesthesia     47
14         Pain in extremity     43
15  SARS-CoV-2 test negative     42
16              Paraesthesia     36
17                     Cough     36
18                Chest pain     35
19          Feeling abnormal     34

In [59]:
dose_one_sym_countdrop = dose_one_sym_count.drop([11, 15])
dose_one_sym_countdrop

                                            0  count
0                                       Death    183
1                                    Dyspnoea    115
2                                     Pyrexia     99
3                                    Headache     94
4                                   Dizziness     91
...                                       ...    ...
1012                     Joint fluid drainage      1
1013                             Irritability      1
1014  Intraductal papillary mucinous neoplasm      1
1015                    Intracranial aneurysm      1
1016                          Abdominal X-ray      1

[1015 rows x 2 columns]

In [60]:
dose_one_sym_countdrop.reset_index(drop=True, inplace=True)
dose_one_sym_countdrop.head(20)

                          0  count
0                     Death    183
1                  Dyspnoea    115
2                   Pyrexia     99
3                  Headache     94
4                 Dizziness     91
5                    Nausea     75
6                   Fatigue     65
7   Unresponsive to stimuli     61
8                  Vomiting     56
9                    Chills     55
10                     Pain     55
11                 Asthenia     52
12            Hypoaesthesia     47
13        Pain in extremity     43
14             Paraesthesia     36
15                    Cough     36
16               Chest pain     35
17         Feeling abnormal     34
18                  Malaise     34
19         Chest discomfort     33

### Dose 2 All Symptoms

In [62]:
# Extracting dose 2 from dose series
dose_two = merge_all.loc[merge_all["VAX_DOSE_SERIES"]=="2"]
dose_two

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
73,918051,COVID19,MODERNA,2,RA,NJ,33.0,F,NaN,NaN,...,NaN,Y,12/30/2020,01/01/2021,2.0,Abdominal pain,Appendicectomy,Appendicitis,Computerised tomogram abdomen abnormal,Laboratory test
74,918051,COVID19,MODERNA,2,RA,NJ,33.0,F,NaN,NaN,...,NaN,Y,12/30/2020,01/01/2021,2.0,Liver function test,Ultrasound abdomen,Ultrasound pelvis,NaN,NaN
225,918277,COVID19,PFIZER\BIONTECH,2,LA,FL,73.0,M,NaN,NaN,...,NaN,N,01/03/2021,01/04/2021,1.0,Muscular weakness,NaN,NaN,NaN,NaN
370,919022,COVID19,MODERNA,2,LA,MD,28.0,M,NaN,NaN,...,Y,N,09/02/2020,09/02/2020,0.0,Autoantibody positive,Blindness unilateral,Computerised tomogram coronary artery,Echocardiogram,Electrocardiogram
371,919022,COVID19,MODERNA,2,LA,MD,28.0,M,NaN,NaN,...,Y,N,09/02/2020,09/02/2020,0.0,Electrocardiogram ambulatory,Magnetic resonance imaging brain,Ophthalmological examination,Postural orthostatic tachycardia syndrome,Pyrexia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4451,976965,COVID19,PFIZER\BIONTECH,2,LA,AZ,45.0,M,NaN,NaN,...,NaN,N,01/13/2021,01/14/2021,1.0,Myalgia,Pyrexia,SARS-CoV-2 test negative,Tachycardia,Troponin increased
4513,981141,COVID19,PFIZER\BIONTECH,2,LA,GA,34.0,F,NaN,NaN,...,NaN,U,01/22/2021,01/23/2021,1.0,Chills,Dyspnoea,Pain,Pyrexia,NaN
4514,981225,COVID19,PFIZER\BIONTECH,2,UN,MD,59.0,F,Y,01/27/2021,...,NaN,N,01/27/2021,01/27/2021,0.0,Abdominal pain,Death,Pulse absent,Unresponsive to stimuli,Vomiting
4519,981912,COVID19,MODERNA,2,UN,CA,67.0,F,Y,01/27/2021,...,NaN,N,01/23/2021,01/23/2021,0.0,Angiogram pulmonary abnormal,Cardiac arrest,Chest pain,Cold sweat,Death
4520,981912,COVID19,MODERNA,2,UN,CA,67.0,F,Y,01/27/2021,...,NaN,N,01/23/2021,01/23/2021,0.0,Endotracheal intubation,Hypotension,Laboratory test,Pallor,Pulmonary embolism

In [63]:
# Combine all columns into one
dose2_combine = pd.concat(map(dose_two.get, ["SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5"])).reset_index(drop=True)
dose2_combine

0                     Abdominal pain
1                Liver function test
2                  Muscular weakness
3              Autoantibody positive
4       Electrocardiogram ambulatory
                    ...
2590              Troponin increased
2591                             NaN
2592                        Vomiting
2593                           Death
2594              Pulmonary embolism
Length: 2595, dtype: object

In [64]:
# Turn it into a dataframe
dose2_combine_df = pd.DataFrame(dose2_combine)
dose2_combine_df

                                 0
0                   Abdominal pain
1              Liver function test
2                Muscular weakness
3            Autoantibody positive
4     Electrocardiogram ambulatory
...                            ...
2590            Troponin increased
2591                           NaN
2592                      Vomiting
2593                         Death
2594            Pulmonary embolism

[2595 rows x 1 columns]

#### Filter by Dates

In [65]:
# Identify dates
doseTwoDates = dose_two["VAX_DATE"]
doseTwoDatesList = list(doseTwoDates.unique())

# Turn into a dataframe for organization
doseTwoDatesDf = pd.DataFrame(doseTwoDatesList)

# Convert to datetime type
doseTwoDatesDf[0]=doseTwoDatesDf[0].astype('datetime64[ns]')

# Organize
doseTwoDatesDf = doseTwoDatesDf.sort_values(by=0)
doseTwoDatesDf.reset_index(drop=True, inplace=True)
doseTwoDatesDf

            0
0  2020-01-04
1  2020-09-02
2  2020-12-17
3  2020-12-18
4  2020-12-20
5  2020-12-21
6  2020-12-22
7  2020-12-23
8  2020-12-26
9  2020-12-28
10 2020-12-29
11 2020-12-30
12 2021-01-01
13 2021-01-02
14 2021-01-03
15 2021-01-04
16 2021-01-05
17 2021-01-06
18 2021-01-07
19 2021-01-08
20 2021-01-09
21 2021-01-10
22 2021-01-11
23 2021-01-12
24 2021-01-13
25 2021-01-14
26 2021-01-15
27 2021-01-16
28 2021-01-17
29 2021-01-18
30 2021-01-19
31 2021-01-20
32 2021-01-21
33 2021-01-22
34 2021-01-23
35 2021-01-24
36 2021-01-25
37 2021-01-27
38        NaT

In [68]:
# Drop weird dates
doseTwoDatesDf_cleaned = doseTwoDatesDf.drop(doseTwoDatesDf.index[0:15])
doseTwoDatesDf_cleaned = doseTwoDatesDf_cleaned.drop([38])
doseTwoDatesDf_cleaned.reset_index(drop=True, inplace=True)
doseTwoDatesDf_cleaned

            0
0  2021-01-04
1  2021-01-05
2  2021-01-06
3  2021-01-07
4  2021-01-08
5  2021-01-09
6  2021-01-10
7  2021-01-11
8  2021-01-12
9  2021-01-13
10 2021-01-14
11 2021-01-15
12 2021-01-16
13 2021-01-17
14 2021-01-18
15 2021-01-19
16 2021-01-20
17 2021-01-21
18 2021-01-22
19 2021-01-23
20 2021-01-24
21 2021-01-25
22 2021-01-27

In [69]:
# Create a column of the converted datetime formate
dose_two_covert_copy = dose_two.copy()
dose_two_covert = dose_two["VAX_DATE"].astype('datetime64[ns]')
dose_two_covert_copy["CONVERTED_DATE"] = dose_two_covert

# Create a desired date list
date_list2 = list(doseTwoDatesDf_cleaned[0])

# Filter out the content based on the content of date list
dose_two_filter = dose_two_covert_copy[dose_two_covert_copy.CONVERTED_DATE.isin(date_list2)]
dose_two_filter.reset_index(drop=True, inplace=True)
dose_two_filter

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,CONVERTED_DATE
0,927360,COVID19,PFIZER\BIONTECH,2,RA,TX,21.0,M,NaN,NaN,...,Y,01/05/2021,01/05/2021,0.0,Chills,Headache,Muscular weakness,Pain,Photosensitivity reaction,2021-01-05
1,927360,COVID19,PFIZER\BIONTECH,2,RA,TX,21.0,M,NaN,NaN,...,Y,01/05/2021,01/05/2021,0.0,Tremor,NaN,NaN,NaN,NaN,2021-01-05
2,928378,COVID19,PFIZER\BIONTECH,2,UN,FL,95.0,F,NaN,NaN,...,N,01/06/2021,01/07/2021,1.0,Dyspnoea,Hospice care,Myocardial infarction,Respiratory tract congestion,Tachycardia,2021-01-06
3,928378,COVID19,PFIZER\BIONTECH,2,UN,FL,95.0,F,NaN,NaN,...,N,01/06/2021,01/07/2021,1.0,Unresponsive to stimuli,NaN,NaN,NaN,NaN,2021-01-06
4,929359,COVID19,PFIZER\BIONTECH,2,LA,FL,76.0,M,Y,01/08/2021,...,N,01/06/2021,01/06/2021,0.0,Breath sounds abnormal,Death,Oxygen saturation decreased,NaN,NaN,2021-01-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,976965,COVID19,PFIZER\BIONTECH,2,LA,AZ,45.0,M,NaN,NaN,...,N,01/13/2021,01/14/2021,1.0,Myalgia,Pyrexia,SARS-CoV-2 test negative,Tachycardia,Troponin increased,2021-01-13
472,981141,COVID19,PFIZER\BIONTECH,2,LA,GA,34.0,F,NaN,NaN,...,U,01/22/2021,01/23/2021,1.0,Chills,Dyspnoea,Pain,Pyrexia,NaN,2021-01-22
473,981225,COVID19,PFIZER\BIONTECH,2,UN,MD,59.0,F,Y,01/27/2021,...,N,01/27/2021,01/27/2021,0.0,Abdominal pain,Death,Pulse absent,Unresponsive to stimuli,Vomiting,2021-01-27
474,981912,COVID19,MODERNA,2,UN,CA,67.0,F,Y,01/27/2021,...,N,01/23/2021,01/23/2021,0.0,Angiogram pulmonary abnormal,Cardiac arrest,Chest pain,Cold sweat,Death,2021-01-23
475,981912,COVID19,MODERNA,2,UN,CA,67.0,F,Y,01/27/2021,...,N,01/23/2021,01/23/2021,0.0,Endotracheal intubation,Hypotension,Laboratory test,Pallor,Pulmonary embolism,2021-01-23

In [70]:
# Get count of patients
dose_two_filter["VAX_DOSE_SERIES"].value_counts()

2    476
Name: VAX_DOSE_SERIES, dtype: int64

In [72]:
# Combine all columns into one
dose2_combine = pd.concat(map(dose_two_filter.get, ["SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5"])).reset_index(drop=True)
# Turn it into a dataframe
dose2_combine_df = pd.DataFrame(dose2_combine)
dose2_combine_df

                            0
0                      Chills
1                      Tremor
2                    Dyspnoea
3     Unresponsive to stimuli
4      Breath sounds abnormal
...                       ...
2375       Troponin increased
2376                      NaN
2377                 Vomiting
2378                    Death
2379       Pulmonary embolism

[2380 rows x 1 columns]

#### Dose 2

In [73]:
# Get the count for each symptom
dose_two_sym = pd.DataFrame(dose2_combine_df.value_counts())
dose_two_sym_count = dose_two_sym.rename(columns={0:"count"})
dose_two_sym_count.reset_index(drop=False, inplace=True)
dose_two_sym_count.head(20)

                           0  count
0                    Pyrexia     55
1                   Headache     51
2                     Chills     47
3                       Pain     46
4                   Dyspnoea     42
5                    Fatigue     37
6                     Nausea     37
7                  Dizziness     28
8                 Chest pain     27
9                   Vomiting     26
10                     Death     22
11                   Myalgia     22
12  SARS-CoV-2 test negative     21
13               Tachycardia     21
14                Arthralgia     20
15                   Syncope     18
16         Pain in extremity     18
17                  Asthenia     17
18             Hyperhidrosis     15
19       Injection site pain     15

In [74]:
dose_two_sym_countdrop = dose_two_sym_count.drop([12])
dose_two_sym_countdrop

                          0  count
0                   Pyrexia     55
1                  Headache     51
2                    Chills     47
3                      Pain     46
4                  Dyspnoea     42
..                      ...    ...
520                Lethargy      1
521            Leukocytosis      1
522            Life support      1
523             Limb injury      1
524  AST/ALT ratio abnormal      1

[524 rows x 2 columns]

In [75]:
dose_two_sym_countdrop.reset_index(drop=True, inplace=True)
dose_two_sym_countdrop.head(20)

                      0  count
0               Pyrexia     55
1              Headache     51
2                Chills     47
3                  Pain     46
4              Dyspnoea     42
5               Fatigue     37
6                Nausea     37
7             Dizziness     28
8            Chest pain     27
9              Vomiting     26
10                Death     22
11              Myalgia     22
12          Tachycardia     21
13           Arthralgia     20
14              Syncope     18
15    Pain in extremity     18
16             Asthenia     17
17        Hyperhidrosis     15
18  Injection site pain     15
19                 Rash     15

### Dose Unknown All Symptoms

In [76]:
# Extracting dose 1 from dose series
dose_unk = merge_all.loc[merge_all["VAX_DOSE_SERIES"]=="UNK"]
dose_unk

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,DISABLE,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
7,916772,COVID19,PFIZER\BIONTECH,UNK,LA,GA,55.0,M,NaN,NaN,...,NaN,U,12/22/2020,12/26/2020,4.0,Feeling abnormal,SARS-CoV-2 test positive,NaN,NaN,NaN
31,917210,COVID19,PFIZER\BIONTECH,UNK,AR,UT,30.0,F,NaN,NaN,...,NaN,N,12/21/2020,12/27/2020,6.0,Blood lactate dehydrogenase increased,C-reactive protein increased,Chest X-ray abnormal,Chills,Computerised tomogram thorax
32,917210,COVID19,PFIZER\BIONTECH,UNK,AR,UT,30.0,F,NaN,NaN,...,NaN,N,12/21/2020,12/27/2020,6.0,Cough,Diarrhoea,Dyspnoea,Fibrin D dimer normal,Lung consolidation
33,917210,COVID19,PFIZER\BIONTECH,UNK,AR,UT,30.0,F,NaN,NaN,...,NaN,N,12/21/2020,12/27/2020,6.0,Lung infiltration,Lung opacity,Procalcitonin increased,Pyrexia,Respiratory viral panel
34,917210,COVID19,PFIZER\BIONTECH,UNK,AR,UT,30.0,F,NaN,NaN,...,NaN,N,12/21/2020,12/27/2020,6.0,SARS-CoV-2 test negative,SARS-CoV-2 test positive,Serum ferritin increased,Skin lesion,Sputum culture
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4509,979990,COVID19,MODERNA,UNK,NaN,OH,63.0,M,Y,01/09/2021,...,NaN,N,01/07/2021,01/09/2021,2.0,Cardiac arrest,NaN,NaN,NaN,NaN
4518,981849,COVID19,MODERNA,UNK,LA,IN,92.0,M,Y,01/16/2021,...,NaN,N,01/13/2021,01/16/2021,3.0,Death,NaN,NaN,NaN,NaN
4525,982354,COVID19,MODERNA,UNK,NaN,NaN,91.0,M,Y,01/23/2021,...,NaN,NaN,12/29/2020,01/23/2021,25.0,Death,NaN,NaN,NaN,NaN
4526,982370,COVID19,MODERNA,UNK,LA,KY,93.0,M,Y,01/16/2021,...,NaN,N,01/14/2021,01/16/2021,2.0,Death,NaN,NaN,NaN,NaN
4530,982517,COVID19,MODERNA,UNK,NaN,NaN,66.0,M,Y,01/25/2021,...,NaN,NaN,01/11/2021,01/25/2021,14.0,Death,NaN,NaN,NaN,NaN

In [77]:
# Combine all columns into one
doseUNK_combine = pd.concat(map(dose_unk.get, ["SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5"])).reset_index(drop=True)
doseUNK_combine

0                            Feeling abnormal
1       Blood lactate dehydrogenase increased
2                                       Cough
3                           Lung infiltration
4                    SARS-CoV-2 test negative
                        ...
3985                                      NaN
3986                                      NaN
3987                                      NaN
3988                                      NaN
3989                                      NaN
Length: 3990, dtype: object

In [78]:
# Turn it into a dataframe
doseUNK_combine_df = pd.DataFrame(doseUNK_combine)
doseUNK_combine_df

                                          0
0                          Feeling abnormal
1     Blood lactate dehydrogenase increased
2                                     Cough
3                         Lung infiltration
4                  SARS-CoV-2 test negative
...                                     ...
3985                                    NaN
3986                                    NaN
3987                                    NaN
3988                                    NaN
3989                                    NaN

[3990 rows x 1 columns]

#### Filter by Dates

In [79]:
# Identify dates
doseUnkDates = dose_unk["VAX_DATE"]
doseUnkDatesList = list(doseUnkDates.unique())

# Turn into a dataframe for organization
doseUnkDatesDf = pd.DataFrame(doseUnkDatesList)

# Convert to datetime type
doseUnkDatesDf[0]=doseUnkDatesDf[0].astype('datetime64[ns]')

# Organize
doseUnkDatesDf = doseUnkDatesDf.sort_values(by=0)
doseUnkDatesDf.reset_index(drop=True, inplace=True)
doseUnkDatesDf

            0
0  2020-01-03
1  2020-01-12
2  2020-10-02
3  2020-12-01
4  2020-12-02
5  2020-12-13
6  2020-12-14
7  2020-12-15
8  2020-12-16
9  2020-12-17
10 2020-12-18
11 2020-12-19
12 2020-12-20
13 2020-12-21
14 2020-12-22
15 2020-12-23
16 2020-12-24
17 2020-12-26
18 2020-12-27
19 2020-12-28
20 2020-12-29
21 2020-12-30
22 2020-12-31
23 2021-01-01
24 2021-01-02
25 2021-01-03
26 2021-01-04
27 2021-01-05
28 2021-01-06
29 2021-01-07
30 2021-01-08
31 2021-01-09
32 2021-01-10
33 2021-01-11
34 2021-01-12
35 2021-01-13
36 2021-01-14
37 2021-01-15
38 2021-01-16
39 2021-01-18
40 2021-01-19
41 2021-01-20
42 2021-01-21
43 2021-01-22
44 2021-01-23
45 2021-01-25
46 2021-01-26
47        NaT

In [82]:
# Drop weird dates
doseUnkDatesDf_cleaned = doseUnkDatesDf.drop(doseUnkDatesDf.index[0:26])
doseUnkDatesDf_cleaned = doseUnkDatesDf_cleaned.drop([47])
doseUnkDatesDf_cleaned.reset_index(drop=True, inplace=True)
doseUnkDatesDf_cleaned

            0
0  2021-01-04
1  2021-01-05
2  2021-01-06
3  2021-01-07
4  2021-01-08
5  2021-01-09
6  2021-01-10
7  2021-01-11
8  2021-01-12
9  2021-01-13
10 2021-01-14
11 2021-01-15
12 2021-01-16
13 2021-01-18
14 2021-01-19
15 2021-01-20
16 2021-01-21
17 2021-01-22
18 2021-01-23
19 2021-01-25
20 2021-01-26

In [84]:
# Create a column of the converted datetime formate
dose_unk_covert_copy = dose_unk.copy()
dose_unk_covert = dose_unk["VAX_DATE"].astype('datetime64[ns]')
dose_unk_covert_copy["CONVERTED_DATE"] = dose_unk_covert

# Create a desired date list
date_list3 = list(doseUnkDatesDf_cleaned[0])

# Filter out the content based on the content of date list
dose_unk_filter = dose_unk_covert_copy[dose_unk_covert_copy.CONVERTED_DATE.isin(date_list3)]
dose_unk_filter.reset_index(drop=True, inplace=True)
dose_unk_filter

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_DOSE_SERIES,VAX_SITE,STATE,AGE_YRS,SEX,DIED,DATEDIED,...,RECOVD,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,CONVERTED_DATE
0,919824,COVID19,PFIZER\BIONTECH,UNK,RA,NaN,23.0,F,NaN,NaN,...,N,01/04/2021,01/04/2021,0.0,Chills,Fatigue,Headache,Malaise,Myalgia,2021-01-04
1,919824,COVID19,PFIZER\BIONTECH,UNK,RA,NaN,23.0,F,NaN,NaN,...,N,01/04/2021,01/04/2021,0.0,Nausea,NaN,NaN,NaN,NaN,2021-01-04
2,924029,COVID19,MODERNA,UNK,NaN,NY,53.0,F,NaN,NaN,...,N,01/06/2021,01/06/2021,0.0,Dizziness,Dysphagia,Heart rate increased,Throat tightness,NaN,2021-01-06
3,924050,COVID19,MODERNA,UNK,NaN,HI,55.0,F,NaN,NaN,...,N,01/06/2021,01/06/2021,0.0,Anaphylactic reaction,Dyspnoea,NaN,NaN,NaN,2021-01-06
4,924464,COVID19,PFIZER\BIONTECH,UNK,NaN,IA,61.0,F,Y,01/06/2021,...,N,01/05/2021,01/06/2021,1.0,Cardiac arrest,Condition aggravated,Haemoptysis,Lung neoplasm malignant,NaN,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,979837,COVID19,PFIZER\BIONTECH,UNK,NaN,NV,76.0,M,Y,01/27/2021,...,N,01/25/2021,01/27/2021,2.0,Pulseless electrical activity,Resuscitation,Ventricular fibrillation,NaN,NaN,2021-01-25
264,979990,COVID19,MODERNA,UNK,NaN,OH,63.0,M,Y,01/09/2021,...,N,01/07/2021,01/09/2021,2.0,Cardiac arrest,NaN,NaN,NaN,NaN,2021-01-07
265,981849,COVID19,MODERNA,UNK,LA,IN,92.0,M,Y,01/16/2021,...,N,01/13/2021,01/16/2021,3.0,Death,NaN,NaN,NaN,NaN,2021-01-13
266,982370,COVID19,MODERNA,UNK,LA,KY,93.0,M,Y,01/16/2021,...,N,01/14/2021,01/16/2021,2.0,Death,NaN,NaN,NaN,NaN,2021-01-14
267,982517,COVID19,MODERNA,UNK,NaN,NaN,66.0,M,Y,01/25/2021,...,NaN,01/11/2021,01/25/2021,14.0,Death,NaN,NaN,NaN,NaN,2021-01-11

In [85]:
# Get count of patients
dose_unk_filter["VAX_DOSE_SERIES"].value_counts()

UNK    268
Name: VAX_DOSE_SERIES, dtype: int64

In [86]:
# Combine all columns into one
doseUNK_combine = pd.concat(map(dose_unk_filter.get, ["SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5"])).reset_index(drop=True)
# Turn it into a dataframe
doseUNK_combine_df = pd.DataFrame(doseUNK_combine)
doseUNK_combine_df

                          0
0                    Chills
1                    Nausea
2                 Dizziness
3     Anaphylactic reaction
4            Cardiac arrest
...                     ...
1335                    NaN
1336                    NaN
1337                    NaN
1338                    NaN
1339                    NaN

[1340 rows x 1 columns]

#### Unknown

In [87]:
# Get the count for each symptom
dose_unk_sym = pd.DataFrame(doseUNK_combine_df.value_counts())
dose_unk_sym_count = dose_unk_sym.rename(columns={0:"count"})
dose_unk_sym_count.reset_index(drop=False, inplace=True)
dose_unk_sym_count.head(20)

                           0  count
0                      Death     32
1                    Pyrexia     23
2                   Dyspnoea     22
3                  Dizziness     18
4                     Nausea     16
5                   Headache     14
6                    Fatigue     14
7   SARS-CoV-2 test positive     12
8                   Vomiting     12
9                    Malaise     11
10                Chest pain     11
11            Intensive care      9
12          Throat tightness      9
13   Unresponsive to stimuli      9
14      Condition aggravated      9
15            Cardiac arrest      8
16         Confusional state      8
17                      Pain      8
18                  Asthenia      8
19                    Chills      7

In [88]:
dose_unk_sym_countdrop = dose_unk_sym_count.drop([7])
dose_unk_sym_countdrop

                        0  count
0                   Death     32
1                 Pyrexia     23
2                Dyspnoea     22
3               Dizziness     18
4                  Nausea     16
..                    ...    ...
384              Lethargy      1
385          Life support      1
386      Lipase increased      1
387   Liver function test      1
388  Abdominal discomfort      1

[388 rows x 2 columns]

In [89]:
dose_unk_sym_countdrop.reset_index(drop=True, inplace=True)
dose_unk_sym_countdrop.head(20)

                          0  count
0                     Death     32
1                   Pyrexia     23
2                  Dyspnoea     22
3                 Dizziness     18
4                    Nausea     16
5                  Headache     14
6                   Fatigue     14
7                  Vomiting     12
8                   Malaise     11
9                Chest pain     11
10           Intensive care      9
11         Throat tightness      9
12  Unresponsive to stimuli      9
13     Condition aggravated      9
14           Cardiac arrest      8
15        Confusional state      8
16                     Pain      8
17                 Asthenia      8
18                   Chills      7
19       Decreased appetite      7

### Export Cleaned Datasets to SQLite

In [90]:
## Create the connection using the imported create_engine function and then invoking the connect method on it
engine = create_engine('sqlite:///doseOneSymptomsUpdated.db', echo=False)
sqlite_connection = engine.connect()

In [91]:
## Set a variable name with the string of a table name
sqlite_doseOneSymptomsUpdated = "doseOneSymptomsUpdated"
dose_one_sym_countdrop.to_sql(sqlite_doseOneSymptomsUpdated, sqlite_connection, if_exists='fail')

In [92]:
## Close the database connection 
sqlite_connection.close()

In [93]:
## Create the connection using the imported create_engine function and then invoking the connect method on it
engine = create_engine('sqlite:///doseTwoSymptomsUpdated.db', echo=False)
sqlite_connection = engine.connect()

In [94]:
## Set a variable name with the string of a table name
sqlite_doseTwoSymptomsUpdated = "doseTwoSymptomsUpdated"
dose_two_sym_countdrop.to_sql(sqlite_doseTwoSymptomsUpdated, sqlite_connection, if_exists='fail')

In [95]:
## Close the database connection 
sqlite_connection.close()

In [96]:
## Create the connection using the imported create_engine function and then invoking the connect method on it
engine = create_engine('sqlite:///doseUnkSymptomsUpdated.db', echo=False)
sqlite_connection = engine.connect()

In [97]:
## Set a variable name with the string of a table name
sqlite_doseUnkSymptomsUpdated = "doseUnkSymptomsUpdated"
dose_unk_sym_countdrop.to_sql(sqlite_doseUnkSymptomsUpdated, sqlite_connection, if_exists='fail')

In [98]:
## Close the database connection 
sqlite_connection.close()